name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Changed to true to ensure all dependencies are pulled
          submodules: true 
          
      - name: Force Latest Submodules
        # This tells GitHub to ignore the "pointing" hash and grab the newest code
        run: |
          git submodule update --init --recursive --remote external/CUE4Parse

      - name: Patch CUE4Parse Culture Crash
        run: |
          # Use sed to comment out the throw line in InternationalizationDictionary.cs
          sed -i "s/throw new KeyNotFoundException(\$'\".*\" is not a valid culture.');/\/\/ throw new KeyNotFoundException(\$'\".*\" is not a valid culture.');/" external/CUE4Parse/CUE4Parse/FileProvider/InternationalizationDictionary.cs
          
          # Verification (Optional: prints the line to logs to make sure it worked)
          grep "is not a valid culture" external/CUE4Parse/CUE4Parse/FileProvider/InternationalizationDictionary.cs

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore UnrealReZen/UnrealReZen.csproj

      - name: Build
        # Using 'publish' instead of 'build' creates a cleaner folder for the .exe
        run: dotnet publish UnrealReZen/UnrealReZen.csproj -c Release -r win-x64 --self-contained /p:PublishSingleFile=true /p:PublishReadyToRun=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnrealReZen-Windows
          # Path to where dotnet publish puts the exe
          path: UnrealReZen/bin/Release/net8.0/win-x64/publish/
