name: build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Changed to true to ensure all dependencies are pulled
          submodules: true 

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore UnrealReZen/UnrealReZen.csproj

      - name: Build
        # Using 'publish' instead of 'build' creates a cleaner folder for the .exe
        run: dotnet publish UnrealReZen/UnrealReZen.csproj -c Release -r win-x64 --self-contained /p:PublishSingleFile=true /p:PublishReadyToRun=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnrealReZen-Windows
          # Path to where dotnet publish puts the exe
          path: UnrealReZen/bin/Release/net8.0/win-x64/publish/
